'use client'

import { useState } from 'react'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'
import { Download } from 'lucide-react'
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer'

// PDF Styles
const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    fontWeight: 'bold',
  },
  section: {
    marginBottom: 15,
  },
  heading: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    marginTop: 15,
  },
  paragraph: {
    marginBottom: 10,
    lineHeight: 1.5,
  },
  metricBox: {
    padding: 10,
    marginBottom: 10,
    border: '1px solid #ccc',
  },
  bold: {
    fontWeight: 'bold',
  },
  comparison: {
    marginTop: 10,
    padding: 15,
    backgroundColor: '#f0f0f0',
  },
})

function SurvivalReportPDF({ patientData, expectedYearsWait, expectedYearsDomino, additionalYears, waitData, dominoData }: any) {
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.title}>Personalized Survival Probability Report</Text>

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.heading}>Patient Information</Text>
          <Text style={pdfStyles.paragraph}>
            <Text style={pdfStyles.bold}>Age:</Text> {patientData.age} years old{'\n'}
            <Text style={pdfStyles.bold}>MELD Score:</Text> {patientData.meld_score}{'\n'}
            <Text style={pdfStyles.bold}>Diagnosis:</Text> {patientData.diagnosis}
          </Text>
        </View>

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.heading}>Key Findings</Text>
          <View style={pdfStyles.metricBox}>
            <Text style={pdfStyles.bold}>Additional Life Expectancy with Domino Liver</Text>
            <Text style={{ fontSize: 20, marginTop: 5 }}>+{additionalYears.toFixed(1)} years</Text>
          </View>
        </View>

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.heading}>Scenario Comparison</Text>

          <View style={{ marginBottom: 15 }}>
            <Text style={pdfStyles.bold}>Option A: Wait for Standard Donor</Text>
            <Text style={pdfStyles.paragraph}>
              • Expected life expectancy: {expectedYearsWait.toFixed(1)} years{'\n'}
              • 6-month survival probability: {waitData[0]?.survival.toFixed(0)}%{'\n'}
              • 10-year survival probability: {waitData[10]?.survival.toFixed(0)}%{'\n'}
              • No metabolic disease risk
            </Text>
          </View>

          <View style={{ marginBottom: 15 }}>
            <Text style={pdfStyles.bold}>Option B: Accept Domino Liver</Text>
            <Text style={pdfStyles.paragraph}>
              • Expected life expectancy: {expectedYearsDomino.toFixed(1)} years{'\n'}
              • Immediate survival probability: {dominoData[0]?.survival.toFixed(0)}%{'\n'}
              • 10-year survival probability: {dominoData[10]?.survival.toFixed(0)}%{'\n'}
              • Metabolic disease symptoms may appear around Year 12
            </Text>
          </View>
        </View>

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.heading}>Survival Probabilities Over Time</Text>
          <Text style={pdfStyles.paragraph}>
            Year | Wait | Domino{'\n'}
            {[0, 5, 10, 15, 20].map(year =>
              `${year.toString().padEnd(4)} | ${waitData[year]?.survival.toFixed(0)}%`.padEnd(10) + ` | ${dominoData[year]?.survival.toFixed(0)}%`
            ).join('\n')}
          </Text>
        </View>

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.heading}>Key Trade-offs</Text>
          <Text style={pdfStyles.paragraph}>
            <Text style={pdfStyles.bold}>Accepting the domino liver offers:</Text>{'\n'}
            ✓ Significantly higher immediate survival chance ({dominoData[0]?.survival.toFixed(0)}% vs {waitData[0]?.survival.toFixed(0)}%){'\n'}
            ✓ Additional {additionalYears.toFixed(1)} years of expected life{'\n'}
            ✓ Better long-term survival prospects{'\n'}
            ⚠ Risk of metabolic disease symptoms after 10-15 years{'\n\n'}
            <Text style={pdfStyles.bold}>Waiting for a standard donor:</Text>{'\n'}
            ✗ High risk of death while waiting{'\n'}
            ✗ Significantly lower survival probabilities{'\n'}
            ✓ No metabolic disease risk
          </Text>
        </View>

        <View style={[pdfStyles.section, { marginTop: 30 }]}>
          <Text style={{ fontSize: 10, color: '#666' }}>
            This report was generated by DominoMatch AI-powered platform for informational purposes.
            Please discuss all treatment options with your medical team before making any decisions.
          </Text>
        </View>
      </Page>
    </Document>
  )
}

export default function CalculatorPage() {
  const [patientData, setPatientData] = useState({
    age: 67,
    meld_score: 32,
    diagnosis: 'Acute liver failure',
    has_comorbidities: true,
  })

  // Calculate survival curves
  const calculateSurvivalCurve = (scenario: 'wait' | 'domino') => {
    const data = []
    const baseSurvival = scenario === 'wait' ? 0.15 : 0.85 // Initial survival probability
    
    for (let year = 0; year <= 20; year++) {
      let survival
      if (scenario === 'wait') {
        // Exponential decay for waiting - high risk of death
        survival = baseSurvival * Math.exp(-0.3 * year)
      } else {
        // Domino: plateau for 10-15 years, then decline due to metabolic disease
        if (year <= 10) {
          survival = baseSurvival - (year * 0.02) // Slow decline
        } else {
          survival = (baseSurvival - 0.2) * Math.exp(-0.15 * (year - 10)) // Faster decline after 10 years
        }
      }
      data.push({
        year,
        survival: Math.max(0, Math.min(1, survival)) * 100,
      })
    }
    return data
  }

  const waitData = calculateSurvivalCurve('wait')
  const dominoData = calculateSurvivalCurve('domino')

  // Calculate key metrics
  const expectedYearsWait = waitData.reduce((sum, d) => sum + d.survival / 100, 0)
  const expectedYearsDomino = dominoData.reduce((sum, d) => sum + d.survival / 100, 0)
  const additionalYears = expectedYearsDomino - expectedYearsWait

  // Find when metabolic symptoms might appear (domino scenario)
  const metabolicOnsetYear = 12 // FAP typically manifests 10-15 years post-transplant

  // Combined data for chart
  const chartData = waitData.map((wait, index) => ({
    year: wait.year,
    'Wait for Standard Donor': wait.survival,
    'Accept Domino Liver': dominoData[index].survival,
  }))

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-6xl mx-auto">
        <h1 className="text-4xl font-bold mb-2">Personalized Survival Calculator</h1>
        <p className="text-gray-600 mb-8">
          Compare survival probabilities: waiting for standard donor vs. accepting domino liver
        </p>

        <div className="grid md:grid-cols-3 gap-8 mb-8">
          {/* Patient Input */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-xl font-bold mb-4">Patient Information</h2>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Age
                </label>
                <input
                  type="number"
                  value={patientData.age}
                  onChange={(e) => setPatientData({ ...patientData, age: parseInt(e.target.value) || 0 })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  MELD Score
                </label>
                <input
                  type="number"
                  value={patientData.meld_score}
                  onChange={(e) => setPatientData({ ...patientData, meld_score: parseInt(e.target.value) || 0 })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Diagnosis
                </label>
                <input
                  type="text"
                  value={patientData.diagnosis}
                  onChange={(e) => setPatientData({ ...patientData, diagnosis: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md"
                />
              </div>
            </div>
          </div>

          {/* Key Metrics */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-xl font-bold mb-4">Expected Outcomes</h2>
            <div className="space-y-4">
              <div className="bg-red-50 rounded-lg p-4">
                <div className="text-sm text-gray-600 mb-1">Wait for Standard Donor</div>
                <div className="text-2xl font-bold text-red-600">
                  {expectedYearsWait.toFixed(1)} years
                </div>
                <div className="text-xs text-gray-500 mt-1">
                  {waitData[0].survival.toFixed(0)}% chance of surviving 6 months
                </div>
              </div>
              <div className="bg-green-50 rounded-lg p-4">
                <div className="text-sm text-gray-600 mb-1">Accept Domino Liver</div>
                <div className="text-2xl font-bold text-green-600">
                  {expectedYearsDomino.toFixed(1)} years
                </div>
                <div className="text-xs text-gray-500 mt-1">
                  {dominoData[0].survival.toFixed(0)}% chance of surviving 10+ years
                </div>
              </div>
              <div className="bg-blue-50 rounded-lg p-4 border-2 border-blue-600">
                <div className="text-sm text-gray-600 mb-1">Additional Life Expectancy</div>
                <div className="text-3xl font-bold text-blue-600">
                  +{additionalYears.toFixed(1)} years
                </div>
                <div className="text-xs text-gray-500 mt-1">
                  Gain by accepting domino liver
                </div>
              </div>
            </div>
          </div>

          {/* Risk Timeline */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-xl font-bold mb-4">Risk Timeline</h2>
            <div className="space-y-3">
              <div>
                <div className="text-sm font-semibold text-gray-700 mb-1">Metabolic Disease Onset</div>
                <div className="text-lg font-bold text-orange-600">Year {metabolicOnsetYear}</div>
                <div className="text-xs text-gray-500 mt-1">
                  Estimated when FAP symptoms may begin to appear
                </div>
              </div>
              <div className="mt-4">
                <div className="text-sm font-semibold text-gray-700 mb-2">Survival Milestones</div>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span>Survive to see grandchildren graduate:</span>
                    <span className="font-bold text-green-600">
                      {dominoData[15]?.survival.toFixed(0)}% (domino) vs {waitData[15]?.survival.toFixed(0)}% (wait)
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>10-year survival:</span>
                    <span className="font-bold text-green-600">
                      {dominoData[10]?.survival.toFixed(0)}% (domino) vs {waitData[10]?.survival.toFixed(0)}% (wait)
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Survival Curve Chart */}
        <div className="bg-white rounded-lg shadow-lg p-6 mb-8">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-bold">Survival Probability Over Time</h2>
            <PDFDownloadLink
              document={
                <SurvivalReportPDF
                  patientData={patientData}
                  expectedYearsWait={expectedYearsWait}
                  expectedYearsDomino={expectedYearsDomino}
                  additionalYears={additionalYears}
                  waitData={waitData}
                  dominoData={dominoData}
                />
              }
              fileName="survival-probability-report.pdf"
              className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              Export Report
            </PDFDownloadLink>
          </div>
          <ResponsiveContainer width="100%" height={400}>
            <LineChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis 
                dataKey="year" 
                label={{ value: 'Years Post-Transplant', position: 'insideBottom', offset: -5 }}
              />
              <YAxis 
                label={{ value: 'Survival Probability (%)', angle: -90, position: 'insideLeft' }}
              />
              <Tooltip 
                formatter={(value: number) => `${value.toFixed(1)}%`}
                labelFormatter={(label) => `Year ${label}`}
              />
              <Legend />
              <Line 
                type="monotone" 
                dataKey="Wait for Standard Donor" 
                stroke="#ef4444" 
                strokeWidth={3}
                dot={false}
              />
              <Line 
                type="monotone" 
                dataKey="Accept Domino Liver" 
                stroke="#10b981" 
                strokeWidth={3}
                dot={false}
              />
              {/* Mark metabolic disease onset */}
              <Line
                type="monotone"
                dataKey="metabolicOnset"
                stroke="#f97316"
                strokeWidth={2}
                strokeDasharray="5 5"
                dot={false}
                data={chartData.map((d, i) => ({
                  ...d,
                  metabolicOnset: i === metabolicOnsetYear ? 100 : null,
                }))}
              />
            </LineChart>
          </ResponsiveContainer>
          <div className="mt-4 text-sm text-gray-600">
            <p className="mb-2"><strong>Red line:</strong> Survival probability if waiting for standard donor (high risk of death while waiting)</p>
            <p className="mb-2"><strong>Green line:</strong> Survival probability with domino liver (plateau for 10-15 years, then gradual decline)</p>
            <p><strong>Orange dashed line:</strong> Estimated metabolic disease symptom onset (Year {metabolicOnsetYear})</p>
          </div>
        </div>

        {/* Trade-off Summary */}
        <div className="bg-gradient-to-r from-blue-600 to-indigo-600 rounded-lg shadow-lg p-8 text-white">
          <h2 className="text-2xl font-bold mb-4">Key Trade-off</h2>
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <h3 className="text-lg font-semibold mb-2">Accept Domino Liver</h3>
              <ul className="space-y-1 text-blue-100">
                <li>✓ {dominoData[0].survival.toFixed(0)}% chance of immediate survival</li>
                <li>✓ Gain {additionalYears.toFixed(1)} expected years of life</li>
                <li>✓ {dominoData[10]?.survival.toFixed(0)}% chance of 10-year survival</li>
                <li>⚠ Metabolic disease symptoms may appear around Year {metabolicOnsetYear}</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold mb-2">Wait for Standard Donor</h3>
              <ul className="space-y-1 text-blue-100">
                <li>✗ Only {waitData[0].survival.toFixed(0)}% chance of surviving 6 months</li>
                <li>✗ {expectedYearsWait.toFixed(1)} expected years of life</li>
                <li>✗ {waitData[10]?.survival.toFixed(0)}% chance of 10-year survival</li>
                <li>✓ No metabolic disease risk</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

